---
plugins:
  - jemoji
repository: aredridel/Story
defaults:
  -
    scope:
      path: "mars-mission"
    values:
      serif_font: "Tinos"
  -
    scope:
      path: "Untitled"
    values:
      layout: fictive
