---
plugins:
  - jemoji
  - jekyll-relative-links
  - jekyll-remote-theme
fictive:
  beacon: true
remote_theme: aredridel/fictive-jekyll
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
